language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libncurses5-dev libncursesw5-dev libpulse-dev \
    libfftw3-dev
